### ISSUE TITLE
Input and Output 

### ISSUE THREAD

**Issue by Winnie09** [KrishnaswamyLab/SAUCIE#11]
Dear author,

Thanks for developing the software! I have a few questions but did not find clear answer from your paper:

1. is the input a count matrix?
2. is the output a count matrix? Has it been normalized by library size, or log2-transformed?

Thanks!

**Comment by mattamodio** [comment]
For scRNAseq data, is would be best to feed in a matrix post-processing, i.e. do library size normalization and square root or log transform to get the values around 0-20. Then, the output is in the same scale as the input, so to turn it back into counts you would have to reverse the square root or log transform.

**Comment by Winnie09** [comment]
Thanks, Matt! This is very helpful!

On Mar 20, 2019, at 1:11 PM, Matt Amodio <notifications@github.com<mailto:notifications@github.com>> wrote:


For scRNAseq data, is would be best to feed in a matrix post-processing, i.e. do library size normalization and square root or log transform to get the values around 0-20. Then, the output is in the same scale as the input, so to turn it back into counts you would have to reverse the square root or log transform.
