### ISSUE TITLE
Better documentation required.

### ISSUE THREAD

**Issue by sameet** [KrishnaswamyLab/SAUCIE#12]
Hi,

I am trying to run SAUCIE.  It turns out from the code that there is no parameter `--fcs`.  There is a parameter called `--format`, but that us undocumented.  Similarly it is not entirely clear what are the lambda values?  Any elaboration will be greatly useful.

Best,
Sameet

**Comment by mattamodio** [comment]
Thank you for your questions. Indeed the correct specification is `--format fcs`, we will correct this note in the readme to reflect the code. The lambda values are explained in the manuscript, but a summary: lambda_b is the coefficient for batch correction, lambda_d and lambda_c are the coefficients for clustering. The lambda_b default works well in most cases, but adjusting lambda_d and lambda_c for the best clustering might involve tuning them. In general, the higher the lambda_c, the fewer clusters you get. I found sliding lambda_c up or down as appropriate while having lambda_d be double lambda_c is the most successful approach.
