### ISSUE TITLE
Analyzing unlabeled data raises error.

### ISSUE THREAD

**Issue by nehcgnay** [KrishnaswamyLab/SAUCIE#2]
Hello, 

I am trying the script with labels = None which raises the following error:

You must feed a value for placeholder tensor 'batches' with dtype int32 and shape [?]

Is it correct to set labels None for unlabeled data?
Thank you in advance!

**Comment by the1mane1event** [comment]
Thanks for your question. Are you using SAUCIE with the parameter _lambda_b_? If so, that performs batch correction, and as such needs the information about which point is in each batch provided in the _labels_ vector.

If you aren't doing batch correction, be sure to not change the _lambda_b_ parameter away from 0. I've added a more helpful exception message for the next update for that specific issue, thanks!

Let me know if this doesn't fully address your issue!

**Comment by nehcgnay** [comment]
Thanks a lot! Yes I use it for batch correction. 
Now I am able to run with batch ID as the labels, but it returns a totally nan array. 
I am using the "run_with_batchcorrection" method in "train_artificial_data.py" by replacing data, labels with mine. The data shape is (20000, 26). Labels are 0 for [:10000]; 1 for [10000: ]. The values in each column of the data are floats from 0 to150. 
Did I miss something?

**Comment by mattamodio** [comment]
Excellent. nan's are probably coming from gradient overflow, which is common when neural networks are given numbers of too large magnitude. We log-normalize our data as a preprocessing step, which I would recommend trying here.
