### ISSUE TITLE
Cluster annotation only "0.0"

### ISSUE THREAD

**Issue by gouinK** [KrishnaswamyLab/SAUCIE#5]
Greetings,

I am able to run the program without any errors, but the output annotates every cell in the dataset as cluster "0.0". I noticed that the Saucie embeddings, when plotted, constitute just a diagonal line with very little range across the axes. I then tried changing the lambda__c and lambda__d to lower values (from the default values to 0.001), but the cluster annotations were still all "0.0" and it no longer output Saucie embedding values (i.e. the columns were blank). 
My dataset consists of ~7700 cells X ~16000 genes in each of 3 samples. Using standard tools like Seurat, the clustering is clear and I have had no issues identifying different cell types using Seurat clustering.
I am running this locally on my mac (OS 10.13) using python 3.5 and tensorflow 1.4.0.

Do you happen to have any suggestions for why this might be happening?
Thanks!

**Comment by mattamodio** [comment]
Hi! This sounds like it is a problem that the neural network is not learning appropriately, as opposed to there being a bug in the code. As such, unfortunately it could be any of a number of things giving the model a hard time. The first thing to check would be probably the most frequent thing to cause this: what are the min/max values of the dataset? Neural networks need the data to be relatively small values, so we like to either take the log or the square root of the data to make it sure there are no values less than roughly -10.0 and no greater than roughly +10.0.

**Comment by gouinK** [comment]
Thanks! I will try running this with the log-transformed data over the weekend and let you know how it goes.

**Comment by lynnyi** [comment]
I am having the same problem even after log transformation of my count data.

**Comment by mattamodio** [comment]
Thanks for the feedback! I've closed this to free the discussion about this in the other thread.
