### ISSUE TITLE
Turn SAUCIE into python package?

### ISSUE THREAD

**Issue by alexblaessle** [KrishnaswamyLab/SAUCIE#8]
Hi,

great stuff! I was wondering if you would like to (or are already in progress to) turn SAUCIE into a proper python package (a proper setup.py and eventually add it to pypi)? I would be open to help you out with it.

Cheers

**Comment by mattamodio** [comment]
Hey Alex, thanks for reaching out! I would love to! If you're interested, send me an email and we can start talking about it!

**Comment by mdanb** [comment]
@alexblaessle @mattamodio was this eventually done? Can't find the package on pypi

**Comment by PingjunChen** [comment]
How does the python package process go on?
